### ISSUE TITLE
How do I make an emoji from the database just as a display?

### ISSUE THREAD

**Issue by productdevbook** [si-newtech/si-grenoble#5]
example

```
<SiEmoji :emoji="📗" :size="24"/>
```

**Comment by productdevbook** [comment]
```
<SiEmoji class="p-px w-5 h-5" :emoji="activity.node?.emoji" />
```

```
  import {SiEmoji} from 'si-grenoble'
 ```
  add and fixed okay ✅. but dont see ts `SiEmoji` :)

**Comment by koyasaeki** [comment]
@productdevbook

First, thank you for using my personal library.
And sorry for inconvenience.

Let me check to be certain, the first example is the following, I think.

```diff
- <SiEmoji :emoji="📗" :size="24"/>
+ <!-- not v-bind -->
+ <SiEmoji emoji="📗" :size="24" />
```

If your issue is caused by this, you don't have to read the passage below.

---

This library is just for tailwind users.
So, we need to install tailwind.

## how to fix this problem

- Not tailwind user => you must create your own library 😢.
- Tailwind v3 user => you can use this library without configuration.
- Tailwind v2 user => just add the following code in your `tailwind.config.js`.

```js
module.exports = {
  purge: {
    safelist: [
      "flex",
      "flex-row",
      "flex-col",
      "absolute",
      "grid",
      "grid-cols-5",
      "grid-cols-8",
      "grid-cols-10",
      "col-start-1",
      "row-start-1",
      "place-content-start",
      "gap-0",
      "justify-items-center",
      "align-center",
      "items-center",
      "w-6",
      "w-8",
      "w-10",
      "h-6",
      "h-8",
      "h-10",
      "h-64",
      "p-0.5",
      "p-1",
      "p-2",
      "pt-1",
      "mt-1",
      "mt-10",
      "mb-4",
      "py-1",
      "px-2",
      "rounded",
      "border",
      "overflow-x-auto",
      "overflow-y-hidden",
      "overflow-y-scroll",
      "bg-gray-200",
      "bg-gray-50",
      "bg-opacity-25"
    ]
  }
};
```

**Comment by productdevbook** [comment]
thank you back ❤️, I'm using tailwindcss 3.0 but I want to make the design a little nicer.

**Comment by productdevbook** [comment]
Tailwind v3 delete `safelist` and design broken
